services:
  client:
    image: node:latest
    ports:
      - "4200:4200"
    volumes:
      - ./client:/client
    container_name: client
    working_dir: /client
    command: sh -c "npm install && npm run start"
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - server
  server:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
    container_name: server
    working_dir: /server
    command: sh -c "npm install && npm run start"